### ISSUE TITLE
What font is used on your screenshots?)

### ISSUE THREAD

**Issue by ogau** [xaverh/theme-qillqaq#4]

**Comment by xaverh** [comment]
This is Input Mono Condensed, which you can get from https://input.fontbureau.com.
I customize it usually like this: https://input.fontbureau.com/download/index.html?customize&fontSelection=fourStyleFamily&regular=InputMonoCondensed-Regular&italic=InputMonoCondensed-Italic&bold=InputMonoCondensed-Bold&boldItalic=InputMonoCondensed-BoldItalic&a=0&g=ss&i=topserif&l=topserif&zero=slash&asterisk=height&braces=0&preset=default&line-height=1.3&email=
